version: '3.4'

services:
  SensorReceiver.api:
    image: fabricioveronez/sensor-receiver-api
    build:
      context: .
      dockerfile: src/SensorReceiver.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - SensorReceiver
    ports:
      - "8181:80"
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_USERNAME: jobUser
      QUEUECONFIG_PASSWORD: jobPwd
      QUEUECONFIG_QUEUE: sensor-event

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3-management
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - SensorReceiver
    environment:
      RABBITMQ_DEFAULT_USER: jobUser
      RABBITMQ_DEFAULT_PASS: jobPwd

  mongodb:
    container_name: mongodb
    image: mongo:4.2.5
    volumes:
        - db_mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - SensorReceiver
    restart: always
    command: --storageEngine wiredTiger
    environment: 
        MONGO_INITDB_ROOT_USERNAME: mongouser
        MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

  SensorReceiver.worker:
    image: fabricioveronez/sensor-receiver-worker
    build:
      context: .
      dockerfile: src/SensorReceiver.Worker/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - SensorReceiver
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_USERNAME: jobUser
      QUEUECONFIG_PASSWORD: jobPwd
      QUEUECONFIG_QUEUE: sensor-event      
      MONGOCLIENT_HOST: mongodb
      MONGOCLIENT_DATABASE: admin
      MONGOCLIENT_USER: mongouser
      MONGOCLIENT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

volumes:
  mq_data:
  db_mongo:

networks:
  SensorReceiver:
    driver: bridge
