apiVersion: batch/v1
kind: Job
metadata:
  name: roleta-job
spec:
  # Quantos pods eu posso criar em paralelo 
  parallelism: 1
  # Quantas vezes eu tolero falhar
  backoffLimit: 100 
  # Quantas vezes eu preciso completar a tarefa pra considerar concluído 
  completions: 2
  # Quanto tempo o pod fica disponível antes de ser removido. Mas o cluster precisa ter o TTLAfterFinished configurado
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
      - name: job
        image: fabricioveronez/roleta
        args:
          - "-w"
          - "15"
          - "-c"
          - "2"
          - "-m"
          - "5"
      restartPolicy: Never # OnFailure

