apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    name: rabbit01
  - port: 5672
    targetPort: 5672    
    name: rabbit02
  type: LoadBalancer
